// Auto-generated API client - do not edit manually
// Generated by orval from OpenAPI spec(#555。マルチサービス構成向けに各サービスの
// 生成結果は ./generated/<サービス名>/ 配下に分かれるが、ここで従来と同じシンボル名で
// 再エクスポートすることで、@api-client を利用する側(web/extension)の import文は
// 変更不要にする)

// legacy-api
export * from './generated/legacy-api/letSBlogAPI.schemas';
export * from './generated/legacy-api/auth/auth';
export * from './generated/legacy-api/posts/posts';
export * from './generated/legacy-api/sites/sites';
export * from './generated/legacy-api/users/users';

// 将来のサービス抽出Issueで追加するターゲットも、ここに re-export を追加していく。
