logging:
  level:
    root: INFO
    com.letsblog.api: INFO
  path: /var/log/lets-blog-api
  json:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

app:
  environment: production
