logging:
  level:
    root: INFO
    com.letsblog.api: INFO
  path: /var/log/lets-blog-api
  json:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

app:
  mail:
    from: ${MAIL_FROM_ADDRESS:noreply@letsblog.example.com}
  environment: production
