CREATE TABLE projects (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  local_site_id BIGINT,
  test_site_id BIGINT,
  production_site_id BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (local_site_id) REFERENCES sites(id) ON DELETE SET NULL,
  FOREIGN KEY (test_site_id) REFERENCES sites(id) ON DELETE SET NULL,
  FOREIGN KEY (production_site_id) REFERENCES sites(id) ON DELETE SET NULL
);

CREATE TABLE project_users (
  project_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  wp_role VARCHAR(50) NOT NULL DEFAULT 'contributor',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (project_id, user_id),
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
