// Auto-generated API client - do not edit manually
// Generated by orval from OpenAPI spec(#555。マルチサービス構成向けに各サービスの
// 生成結果は ./generated/<サービス名>/ 配下に分かれるが、ここで従来と同じシンボル名で
// 再エクスポートすることで、@api-client を利用する側(web/extension)の import文は
// 変更不要にする)

// issue #583 で legacy-api を削除した。ここにあった再エクスポート
// (authentication / health / ai / project / project-ai-model / project-api-key /
// project-user)は、それぞれの所有サービスの spec から生成されるものへ置き換わる。
//   - 初回セットアップ(/api/auth/setup・setup-status)・プロジェクトメンバー → identity
//   - 画像生成(/api/ai/image・image-options)・ai-models の画像/ComfyUI・画像設定 → media
//   - 画像生成プロンプト・api-keys/brave-search-api-key → ai
//   - api-keys/github-token → project
//   - api-keys/google-analytics・adsense → analytics
// 各サービスの spec は開発スタックを新コードで起動したうえで
// scripts/generate-api-client.sh を回すと更新される(docs/API_CLIENT_GENERATION.md)。

// log-writer(ログの所有権を完全移管、#572)
export * from './generated/log-writer/openAPIDefinition.schemas';
export * from './generated/log-writer/audit-log-controller/audit-log-controller';
export * from './generated/log-writer/operation-log-controller/operation-log-controller';
export * from './generated/log-writer/frontend-error-log-controller/frontend-error-log-controller';

// media(ComfyUI画像生成・draw.ioダイアグラム・PlantUML/Recharts/Penpotレンダリングの所有権を
// media-serviceへ移管、#573 stage1)
export * from './generated/media/openAPIDefinition.schemas';
export * from './generated/media/generated-image-controller/generated-image-controller';
export * from './generated/media/diagram-controller/diagram-controller';
export * from './generated/media/render-controller/render-controller';
export * from './generated/media/comfy-ui-checkpoint-controller/comfy-ui-checkpoint-controller';
export * from './generated/media/media-controller/media-controller';
export * from './generated/media/project-media-garbage-collection-controller/project-media-garbage-collection-controller';

// mediaのGeneratedImageController.list/DiagramController.listと、log-writerのAuditLogController.list/
// OperationLogController.listは、いずれもJavaのメソッド名が単に"list"であるため、orvalの汎用命名
// (関数名・クエリパラメータ型・レスポンス型・URL組み立て関数)が偶然一致し衝突する(サービスをまたいだ
// 名前空間を持たないorvalのマルチターゲット生成の既知の制約、#573で最初に顕在化)。現時点でこれらの
// シンボルを`@api-client`から名前で直接importしている呼び出し元は無いため、明示的にlog-writer側を正として
// 再エクスポートし曖昧性を解消する(将来他サービスでも同名衝突が起きた場合は同じパターンで解消すること)。
// 同様にmediaのDiagramController.deleteも、Javaのメソッド名が単に"delete"であるため生成名(_delete/
// getDeleteUrl)がorvalの命名衝突を起こしうる(#576でcontent-serviceのCustomTagController.deleteを
// 追加した際に顕在化)。こちらは_delete/getDeleteUrlという識別子を`@api-client`から名前でimportしている
// 呼び出し元が無いため、明示的にmedia側を正として再エクスポートし曖昧性を解消する
// (content側はcustom-tagセクションでdeleteCustomTagとして別名エクスポートする)。
export type {
  ListParams,
  List1Params,
} from './generated/log-writer/openAPIDefinition.schemas';
export {
  list1,
  getList1Url,
} from './generated/log-writer/audit-log-controller/audit-log-controller';
export type {
  list1Response,
  list1Response200,
  list1ResponseSuccess,
} from './generated/log-writer/audit-log-controller/audit-log-controller';
export {
  list,
  getListUrl,
} from './generated/log-writer/operation-log-controller/operation-log-controller';
export type {
  listResponse,
  listResponse200,
  listResponseSuccess,
} from './generated/log-writer/operation-log-controller/operation-log-controller';
export {
  _delete,
  getDeleteUrl,
} from './generated/media/diagram-controller/diagram-controller';
export type {
  _deleteResponse,
  _deleteResponse200,
  _deleteResponseSuccess,
} from './generated/media/diagram-controller/diagram-controller';
// 同じ理由(Javaのメソッド名が単に"create"/"create1"/"delete1"であることによる衝突)で、mediaの
// GeneratedImageController.create/DiagramController.create(diagramの新規作成)/
// ProjectMediaGarbageCollectionController.delete(GC実行)も、#576でcontent-serviceの
// CustomTagController.create/CustomTagTemplateController.create/CustomTagTemplateController.deleteを
// 追加した際に生成名(create/create1/delete1等)が衝突した。既存(media)側を正として再エクスポートし、
// content側は各セクションで別名エクスポートする。
export {
  create,
  getCreateUrl,
} from './generated/media/generated-image-controller/generated-image-controller';
export type {
  createResponse,
  createResponse201,
  createResponseSuccess,
} from './generated/media/generated-image-controller/generated-image-controller';
export {
  create1,
  getCreate1Url,
} from './generated/media/diagram-controller/diagram-controller';
export type {
  create1Response,
  create1Response200,
  create1ResponseSuccess,
} from './generated/media/diagram-controller/diagram-controller';
export {
  delete1,
  getDelete1Url,
} from './generated/media/project-media-garbage-collection-controller/project-media-garbage-collection-controller';
export type {
  delete1Response,
  delete1Response200,
  delete1ResponseSuccess,
} from './generated/media/project-media-garbage-collection-controller/project-media-garbage-collection-controller';

// ai(LLM呼び出し・記事プラン・generation_jobsの所有権をai-serviceへ移管、#574)。
// InternalAiGenerationController/InternalProjectAiSettingsControllerはlegacy-api→ai-serviceの
// 内部ブリッジ専用(/api/ai/internal/**、/api/internal/ai/**)で、gatewayからは到達不能かつ
// web/extensionが呼ぶ想定もないため、他サービスと同様にopenAPIDefinition.schemas経由でスキーマは
// 共有されるが、コントローラ自体はここでは再エクスポートしない。
export * from './generated/ai/openAPIDefinition.schemas';
export * from './generated/ai/ai-controller/ai-controller';
export * from './generated/ai/article-plan-controller/article-plan-controller';
export * from './generated/ai/project-llm-model-controller/project-llm-model-controller';

// GenerationJobController(ai)のlist/getは、log-writer/mediaのlist集約と同様に
// 汎用的な関数名がAuditLogController/OperationLogController/GeneratedImageController等と衝突しうる
// ため、明示的に再エクスポートして曖昧性を防ぐ(既存のlist衝突解消コメント参照)。
// create/updateは認可欠如のため/api/internal/ai/generation-jobsへ移管され、gatewayから到達不能に
// なった(InternalGenerationJobControllerのJavadoc参照)。それに伴いopenapi/ai.jsonの
// /api/generation-jobsもgetのみを定義するようになり、生成元のgeneration-job-controller.tsも
// list/getしかエクスポートしないため、ここでのcreate/updateの再エクスポートは削除する(#1299)。
export {
  list as listGenerationJobs,
  get as getGenerationJob,
  getListUrl as getListGenerationJobsUrl,
  getGetUrl as getGetGenerationJobUrl,
} from './generated/ai/generation-job-controller/generation-job-controller';
export type {
  listResponse as listGenerationJobsResponse,
  getResponse as getGenerationJobResponse,
} from './generated/ai/generation-job-controller/generation-job-controller';

// content(記事本文(posts)・カスタムタグ・Markdownレンダリング・記事プレビュー・コンテンツキャッシュの
// 所有権をcontent-serviceへ移管、#576)。InternalPostBridgeController/InternalPreviewSkeletonController/
// InternalProjectContentSettingsController/InternalPublishPipelineControllerはlegacy-api↔content-service
// の内部ブリッジ専用(/api/internal/content/**)で、gatewayからは到達不能かつweb/extensionが呼ぶ想定も
// ないため、他サービスの内部ブリッジコントローラと同様にここでは再エクスポートしない。
export * from './generated/content/openAPIDefinition.schemas';
export * from './generated/content/article-preview-controller/article-preview-controller';
export * from './generated/content/content-cache-controller/content-cache-controller';
export * from './generated/content/custom-tag-controller/custom-tag-controller';
export * from './generated/content/custom-tag-template-controller/custom-tag-template-controller';
export * from './generated/content/metadata/metadata';
export * from './generated/content/post-controller/post-controller';
export * from './generated/content/project-custom-tag-controller/project-custom-tag-controller';

// content-service内で複数コントローラの"list"系メソッドがorvalによりlist/list1/list2/list3として
// 生成され(既存のlist衝突解消コメント参照)、うちlist/list1はlog-writerが既に正としているシンボルと
// 衝突する。同様にCustomTagController.deleteはJavaのメソッド名が単に"delete"であるため、mediaの
// DiagramController.deleteと生成名(_delete/getDeleteUrl)が衝突する。明示的に別名で再エクスポートして
// 曖昧性を解消する。
export {
  list as listCustomTags,
  getListUrl as getListCustomTagsUrl,
  _delete as deleteCustomTag,
  getDeleteUrl as getDeleteCustomTagUrl,
  create as createCustomTag,
  getCreateUrl as getCreateCustomTagUrl,
} from './generated/content/custom-tag-controller/custom-tag-controller';
export type {
  listResponse as listCustomTagsResponse,
  _deleteResponse as deleteCustomTagResponse,
  createResponse as createCustomTagResponse,
} from './generated/content/custom-tag-controller/custom-tag-controller';
export {
  list1 as listCustomTagTemplates,
  getList1Url as getListCustomTagTemplatesUrl,
  create1 as createCustomTagTemplate,
  getCreate1Url as getCreateCustomTagTemplateUrl,
  delete1 as deleteCustomTagTemplate,
  getDelete1Url as getDeleteCustomTagTemplateUrl,
} from './generated/content/custom-tag-template-controller/custom-tag-template-controller';
export type {
  list1Response as listCustomTagTemplatesResponse,
  create1Response as createCustomTagTemplateResponse,
  delete1Response as deleteCustomTagTemplateResponse,
} from './generated/content/custom-tag-template-controller/custom-tag-template-controller';

// #739 の時点では legacy-api の内部ブリッジコントローラが ai/content と同じDTOを参照しており、
// legacy-api の schemas にも同名の型が生成されて衝突していた。issue #583 で legacy-api を
// 削除したので衝突源は無くなったが、これらの型を所有するのは ai/content 側であることを
// 明示するため、再エクスポート自体は残す。
export type { GenerationJobResponse, PlanChatMessage } from './generated/ai/openAPIDefinition.schemas';
export type { RoleOptionResponse } from './generated/content/openAPIDefinition.schemas';

// analytics(#578)・project(#577)・publishing(#707/#708/#712)・platform(#693〜#696)・
// identity(#561)の生成物は openapi/*.json と packages/api-client/src/generated/ に揃っているが、
// ここからの再エクスポートはまだ行っていない(issue #739のスコープは生成パイプラインの追随まで)。
// 再エクスポートには、上のlist/create/delete系で繰り返し起きているサービス跨ぎの名前衝突を
// 5サービス分まとめて解消する必要があり、独立した作業になるため別Issueで扱う。
// 現時点でこれらを`@api-client`から利用している呼び出し元は無い。
//
// 将来のサービス抽出Issueで追加するターゲットも、ここに re-export を追加していく。

// ---- 以下 issue #809 で追加(analytics/project/publishing/platform/identity) ----
// 内部ブリッジ(/api/internal/**)のコントローラは、既存方針どおり再エクスポートしない。

// analytics(アクセス解析・AdSense、#578)
export * from './generated/analytics/openAPIDefinition.schemas';
export * from './generated/analytics/project-dashboard-controller/project-dashboard-controller';

// identity(ユーザー・ロール・自ユーザー情報、#561)
export * from './generated/identity/openAPIDefinition.schemas';
export * from './generated/identity/identity-controller/identity-controller';
export * from './generated/identity/role-controller/role-controller';
export * from './generated/identity/users/users';

// project(プロジェクト・サイト・SSH鍵・静的コンテンツ・タグデザイン設定、#577)
export * from './generated/project/openAPIDefinition.schemas';
export * from './generated/project/project-controller/project-controller';
export * from './generated/project/sites/sites';
export * from './generated/project/ssh-key-pair-controller/ssh-key-pair-controller';
export * from './generated/project/static-content/static-content';
export * from './generated/project/tag-design-setting-controller/tag-design-setting-controller';

// publishing(記事公開・プレビュー・タクソノミ・一括管理、#707/#708/#712)
export * from './generated/publishing/openAPIDefinition.schemas';
export * from './generated/publishing/article-preview-controller/article-preview-controller';
export * from './generated/publishing/bulk-management-controller/bulk-management-controller';
export * from './generated/publishing/post-controller/post-controller';
export * from './generated/publishing/taxonomy-controller/taxonomy-controller';

// platform(システム設定・バックアップ・ダッシュボード・VSCode拡張配布、#693〜#696)
export * from './generated/platform/openAPIDefinition.schemas';
export * from './generated/platform/app-setting-controller/app-setting-controller';
export * from './generated/platform/backup-controller/backup-controller';
export * from './generated/platform/dashboard-controller/dashboard-controller';
export * from './generated/platform/system-setting-controller/system-setting-controller';
export * from './generated/platform/vscode-extension-controller/vscode-extension-controller';

// ---- issue #809: 5サービス追加に伴う名前衝突の解消 ----
//
// orvalのマルチターゲット生成はサービスを跨いだ名前空間を持たないため、Javaのメソッド名が
// list/create/update/delete/get/resolve のように汎用的だと、複数サービスで同一のシンボル名
// (関数名・URL組み立て関数・レスポンス型)が生成される(#573で最初に顕在化、#574/#576でも再発)。
//
// **どちらを正とするか**: いずれも「既にエクスポートされていた側(先に追加されたサービス)」を正とする。
// 新規追加の5サービスを優先すると、`@lets-blog/api-client` の既存の公開シンボルが指す先が
// 黙って別サービスのクライアントへ入れ替わる。呼び出し元は型エラーにならないまま
// 別サービスを叩くことになり、最も気付きにくい壊れ方をする。既存側を正としておけば、
// 公開APIの意味は変わらず、新サービス側のシンボルが名前で引けないだけに留まる。
//
// 新サービス側のクライアントが必要になったら、そのときに使う側の事情に合わせて
// `export { x as yFromProject }` の形で別名エクスポートを足すこと
// (既存のcontent側 deleteCustomTag と同じパターン)。
export type {
  BraveSearchApiKeyStatusResponse,
  CategoryOption,
  SetBraveSearchApiKeyRequest,
} from './generated/ai/openAPIDefinition.schemas';
export {
  getResolveUrl,
  resolve,
} from './generated/content/content-cache-controller/content-cache-controller';
export type {
  resolveResponse,
  resolveResponse200,
  resolveResponseSuccess,
} from './generated/content/content-cache-controller/content-cache-controller';
export {
  generate,
  getGenerateUrl,
  getUpdate1Url,
  update1,
} from './generated/content/custom-tag-controller/custom-tag-controller';
export type {
  createResponse200,
  generateResponse,
  generateResponse200,
  generateResponseSuccess,
  update1Response,
  update1Response200,
  update1ResponseSuccess,
} from './generated/content/custom-tag-controller/custom-tag-controller';
export {
  getPublishUrl,
  publish,
} from './generated/content/custom-tag-template-controller/custom-tag-template-controller';
export type {
  publishResponse,
  publishResponse200,
  publishResponseSuccess,
} from './generated/content/custom-tag-template-controller/custom-tag-template-controller';
export type {
  ThemeSkeletonResponse,
} from './generated/content/openAPIDefinition.schemas';
export {
  getList3Url,
  list3,
} from './generated/content/post-controller/post-controller';
export type {
  list3Response,
  list3Response200,
  list3ResponseSuccess,
} from './generated/content/post-controller/post-controller';
export {
  getList2Url,
  list2,
} from './generated/content/project-custom-tag-controller/project-custom-tag-controller';
export type {
  list2Response,
  list2Response200,
  list2ResponseSuccess,
} from './generated/content/project-custom-tag-controller/project-custom-tag-controller';
export type {
  _deleteResponse204,
} from './generated/identity/users/users';
export {
  delete2,
  getDelete2Url,
} from './generated/media/comfy-ui-checkpoint-controller/comfy-ui-checkpoint-controller';
export type {
  delete2Response,
  delete2Response200,
  delete2ResponseSuccess,
} from './generated/media/comfy-ui-checkpoint-controller/comfy-ui-checkpoint-controller';
export {
  get,
  getGetUrl,
  getUpdateUrl,
  update,
} from './generated/media/diagram-controller/diagram-controller';
export type {
  getResponse,
  getResponse200,
  getResponseSuccess,
  updateResponse,
  updateResponse200,
  updateResponseSuccess,
} from './generated/media/diagram-controller/diagram-controller';
export type {
  MediaUploadResult,
} from './generated/media/openAPIDefinition.schemas';
export type {
  WpCliInstallResult,
} from './generated/project/openAPIDefinition.schemas';
