-- 一括管理・環境間比較機能(BulkManagementService等)一式のpublishing-serviceへの移管(issue #708、
-- Epic #551 C6-2)に伴う、bulk_operation_logsテーブルの所有権決定。
--
-- issue #572(C3)時点では、bulk_operation_logsはprojectsテーブル(当時legacy-api所有)へのFK
-- (fk_bulk_operation_logs_project、V16マイグレーション)を持つ一括WordPress同期のワークフロー状態で
-- あり、純粋な追記型ログではないという理由で、log-writerへの完全移管(#572)の対象外とし、
-- 「将来のpublishing-service(C6)に属する」とだけ事前決定していた(BulkOperationLog.javaの
-- Javadoc参照)。
--
-- issue #708の実装時点で、以下2点を確認した。
--   1. Project本体の所有権がproject-serviceへ移った(issue #577 stage2)ことに伴い、
--      V77__drop_project_service_tables.sqlが既にfk_bulk_operation_logs_project FKを削除済みで
--      あり、#572時点の技術的制約(ADR-0004のクロススキーマFK禁止)は既に解消している。
--   2. BulkOperationLogクラスはJPAエンティティとしてマッピングされておらず、対応するRepositoryも
--      存在しない。issue #184で操作ログはoperation_logsへ一本化済みであり、bulk_operation_logs
--      テーブルへ実際に永続化するコードパスは存在しない。
--
-- 以上より、物理テーブル自体が不要と判断し、legacy-api(lets_blogスキーマ)側のテーブルを削除する。
-- issue #184で廃止済みの履歴閲覧・replay機能を復活させる意図はないため、publishing-service側
-- (lbs_publishingスキーマ)への再作成は行わない。

DROP TABLE IF EXISTS bulk_operation_logs;
